"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tmrm = require("azure-pipelines-task-lib/mock-run");
var path = require("path");
console.log('running: ');
var taskPath = path.join(__dirname, '..', 'index.js');
var tmr = new tmrm.TaskMockRunner(taskPath);
var CustomDotCoverPath = path.join(__dirname, '..\\download\\CommandLineTools-2020-1-3');
console.log('download: ' + CustomDotCoverPath);
tmr.setInput('CustomDotCoverPath', CustomDotCoverPath);
var TargetExecutable = 'C:\\Program Files\\dotnet\\dotnet.exe';
console.log('TargetExecutable: ' + TargetExecutable);
tmr.setInput('TargetExecutable', TargetExecutable);
var TargetArguments = path.join(__dirname, 'testProjects\\bin\\Debug\\netcoreapp3.1\\testProjects.dll');
console.log('TargetArguments: ' + TargetArguments);
tmr.setInput('TargetArguments', TargetArguments);
var TargetWorkingDir = path.join(__dirname, '..\\download\\TargetWorkingDir');
console.log('TargetWorkingDir: ' + TargetWorkingDir);
tmr.setInput('TargetWorkingDir', TargetWorkingDir);
var Output = path.join(__dirname, '..\\download\\Output');
console.log('Output: ' + Output);
tmr.setInput('Output', Output);
var ReportType = 'xml';
console.log('ReportType: ' + ReportType);
tmr.setInput('ReportType', ReportType);
tmr.run();
